const TableData = 
[
    { "sr": "1", "item": "Pohe", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "2", "item": "Upma", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "3", "item": "Meduwada Sambar", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "4", "item": "Idli Sambar", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "5", "item": "Batata Wada Sambar", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "6", "item": "Single Idli Sambar", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "7", "item": "Single Meduwada Sambar", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "8", "item": "Single Batata Wada Sambar", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "9", "item": "Bread Patis", "quantity": "", "price": "₹15", "total": "" },
    { "sr": "10", "item": "Samosa", "quantity": "", "price": "₹15", "total": "" },
    { "sr": "11", "item": "Wada Pav", "quantity": "", "price": "₹15", "total": "" },
    { "sr": "12", "item": "Maggi", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "13", "item": "Veg Maggi", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "14", "item": "Cheese Maggi", "quantity": "", "price": "₹35", "total": "" },
    { "sr": "15", "item": "Veg Cheese Maggi", "quantity": "", "price": "₹45", "total": "" },
    { "sr": "16", "item": "Cream Roll/ BreadRoll", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "17", "item": "Poli Bhaji", "quantity": "", "price": "₹40", "total": "" },
    { "sr": "18", "item": "Dal Rice", "quantity": "", "price": "₹40", "total": "" },
    { "sr": "19", "item": "Butter Milk", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "20", "item": "Poli", "quantity": "", "price": "₹6", "total": "" },
    { "sr": "21", "item": "Bhaji Plate / Rice / Dal Plate", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "22", "item": "Limbu Sarbat", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "23", "item": "Thali", "quantity": "", "price": "₹70", "total": "" },
    { "sr": "24", "item": "Dahi", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "25", "item": "Mango / Aam Panha / Guava Drink", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "26", "item": "Lassi", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "27", "item": "Flavour Milk", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "28", "item": "Mazha / Apple Drink 150ml", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "29", "item": "Cold Drinks", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "30", "item": "Minutemiad Juices", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "31", "item": "Water 500ml", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "32", "item": "Water 1L Bottle", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "33", "item": "Shrikhand", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "34", "item": "Mazha 250ml", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "35", "item": "Nestle Cold Coffee", "quantity": "", "price": "₹40", "total": "" },
    { "sr": "36", "item": "Nestle Mylo Drink", "quantity": "", "price": "₹40", "total": "" },
    { "sr": "37", "item": "Nestle Ice Tea", "quantity": "", "price": "₹30", "total": "" },
    { "sr": "38", "item": "Munch", "quantity": "", "price": "₹5", "total": "" },
    { "sr": "39", "item": "Kitkat", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "40", "item": "Sweet Dish", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "41", "item": "Tea", "quantity": "", "price": "₹10", "total": "" },
    { "sr": "42", "item": "Coffee", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "43", "item": "Bournvita", "quantity": "", "price": "₹25", "total": "" },
    { "sr": "44", "item": "Plain Milk / Haldi Milk", "quantity": "", "price": "₹20", "total": "" },
    { "sr": "45", "item": "Paneer Sabji", "quantity": "", "price": "₹35", "total": "" },
]

export default TableData;